services:
  app:
    image: backend:latest
    container_name: testcorporation_php
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "127.0.0.1:9000:9000"   # php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/.env
      - ./storage:/var/www/storage
      - public_assets:/var/www/public
    networks:
      - testcorporation
    depends_on:
      - rediskv

  nginx:
    image: nginx:alpine
    container_name: testcorporation_nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage:/var/www/storage
      - public_assets:/var/www/public
    networks:
      - testcorporation

  rediskv:
    image: redis:latest
    restart: always
    container_name: testcorporation_redis
    ports:
      - "127.0.0.1:8379:6379"
    networks:
      - testcorporation

  horizon:
    image: backend:latest
    restart: always
    container_name: testcorporation_horizon
    depends_on:
      - rediskv
    pre_stop:
      -   command: php artisan horizon:terminate
    command: php artisan horizon
    volumes:
      - ./storage:/var/www/storage
      - ./.env:/var/www/.env
    networks:
      - testcorporation

  schedule:
    image: backend:latest
    restart: always
    container_name: testcorporation_schedule
    depends_on:
      - rediskv
    command: php artisan schedule:work
    volumes:
      - ./storage:/var/www/storage
      - ./.env:/var/www/.env
    networks:
      - testcorporation

networks:
  testcorporation:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  public_assets:
