- name: Create Prometheus config directory
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.51.0/prometheus-2.51.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Symlink binaries
  file:
    src: "/opt/prometheus-2.51.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - prometheus
    - promtool

- name: Copy config
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:9100']

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus

      [Install]
      WantedBy=multi-user.target

- name: Ensure data dir
  file:
    path: /var/lib/prometheus
    state: directory

- name: Start and enable Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
