- name: Download Grafana .deb package
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_10.4.1_amd64.deb
    dest: /tmp/grafana.deb

- name: Install Grafana package
  apt:
    deb: /tmp/grafana.deb

- name: Enable and start Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started
